In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv(r"d:\Startup\Project\ai-career-coach\data\processed\jobs_cleaned.csv")
df.columns

Index(['Job Title', 'Company Name', 'Location', 'Experience Required',
       'Salary', 'Skills Required', 'Job Description', 'Posted Date',
       'Scrape Date', 'Job Link', 'Source Platform', 'Standardized_Job_Title',
       'days_sinced_posted', 'salary_min', 'salary_max', 'salary_avg',
       'Experience_Years'],
      dtype='object')

In [72]:
df["combined_text"] = (
    df["Standardized_Job_Title"].fillna("") + " " +
    df["Job Description"].fillna("") + " " +
    df["Skills Required"].fillna("")
)

In [73]:
df["Combined_text"][0]

'data analyst are you a detail oriented individual with a passion for research and a good understanding of national and local geography this opportunity allows you to work at your own pace and from the comfort of your own home key responsibilities  working on a project aimed at enhancing the content and quality of digital maps that are used by millions of people worldwide  completing research and evaluation tasks in a web based environment such as verifying and comparing data and determining the relevance and accuracy of information join us today and be part of a dynamic and innovative team that is making a difference in the world telus digital ai community our global ai community is a vibrant network of  million contributors from diverse backgrounds who help our customers collect enhance train translate and localize content to build better ai models become part of our growing community and make an impact supporting the machine learning models of some of the world s largest brands qualification path no previous professional experience is required to apply to this role however working on this project will require you to pass the basic requirements and go through a standard assessment process this is a part time long term project and your work will be subject to our standard quality assurance checks during the term of this agreement assessment in order to be hired into the program you ll take an open book qualification exam that will determine your suitability for the position and complete id verification our team will provide you with guidelines and learning materials before your qualification exam you will be required to complete the exam in a specific timeframe but at your convenience english proficiency spoken english proficiency written punjabi proficiency spoken punjabi proficiency written artificial intelligence'

In [ ]:
#removed punctuation and converted to lowercase
df["Combined_text"] = (df["Combined_text"].str.lower()
                       .apply(lambda x: re.sub(r'[^a-zA-Z0-9\s]', ' ', x)))

In [6]:
#\xa0\xa0\r\n\xa0\r\n \r\n\r\n\r\n2\r\n\xa0\xa0\r\n\xa0\xa0\xa0\r\n\xa0\r\n\r\n\xa0\xa0\r\n\nIn removing these characters, we are essentially cleaning the text data by eliminating non-alphanumeric characters and extra whitespace. This can help in standardizing the text for further analysis, such as tokenization, keyword extraction, or machine learning tasks.

In [7]:
df["Combined_text"] = df['Combined_text'].apply(lambda x : re.sub(r'[\r\n\xa0]+' , ' ' , x)).str.strip()

In [8]:
df["Combined_text"][0]

'data analyst are you a detail oriented individual with a passion for research and a good understanding of national and local geography  this opportunity allows you to work at your own pace and from the comfort of your own home  key responsibilities   1  working on a project aimed at enhancing the content and quality of digital maps that are used by millions of people worldwide  2  completing research and evaluation tasks in a web based environment such as verifying and comparing data  and determining the relevance and accuracy of information  join us today and be part of a dynamic and innovative team that is making a difference in the world  telus digital ai community  our global ai community is a vibrant network of 1 million  contributors from diverse backgrounds who help our customers collect  enhance  train  translate  and localize content to build better ai models  become part of our growing community and make an impact supporting the machine learning models of some of the world s largest brands  qualification path  no previous professional experience is required to apply to this role  however  working on this project will require you to pass the basic requirements and go through a standard assessment process  this is a part time long term project and your work will be subject to our standard quality assurance checks during the term of this agreement  assessment  in order to be hired into the program  you ll take an open book qualification exam that will determine your suitability for the position and complete id verification  our team will provide you with guidelines and learning materials before your qualification exam  you will be required to complete the exam in a specific timeframe but at your convenience    english proficiency  spoken     english proficiency  written     punjabi proficiency  spoken     punjabi proficiency  written     artificial intelligence'

In [9]:
df["Combined_text"] = df['Combined_text'].apply(lambda x: re.sub(r'\s+', ' ', x).strip())

In [10]:
df['Combined_text'] = df["Combined_text"].apply(lambda x: re.sub(r'\b\d+\b', '', x))

In [11]:
df["Combined_text"][0]

'data analyst are you a detail oriented individual with a passion for research and a good understanding of national and local geography this opportunity allows you to work at your own pace and from the comfort of your own home key responsibilities  working on a project aimed at enhancing the content and quality of digital maps that are used by millions of people worldwide  completing research and evaluation tasks in a web based environment such as verifying and comparing data and determining the relevance and accuracy of information join us today and be part of a dynamic and innovative team that is making a difference in the world telus digital ai community our global ai community is a vibrant network of  million contributors from diverse backgrounds who help our customers collect enhance train translate and localize content to build better ai models become part of our growing community and make an impact supporting the machine learning models of some of the world s largest brands qualification path no previous professional experience is required to apply to this role however working on this project will require you to pass the basic requirements and go through a standard assessment process this is a part time long term project and your work will be subject to our standard quality assurance checks during the term of this agreement assessment in order to be hired into the program you ll take an open book qualification exam that will determine your suitability for the position and complete id verification our team will provide you with guidelines and learning materials before your qualification exam you will be required to complete the exam in a specific timeframe but at your convenience english proficiency spoken english proficiency written punjabi proficiency spoken punjabi proficiency written artificial intelligence'

In [12]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [13]:
import nltk
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [14]:
df['tokens'] = df["Combined_text"].apply(word_tokenize)

In [15]:
df['tokens']

0      [data, analyst, are, you, a, detail, oriented,...
1      [data, analyst, a, day, in, the, life, of, an,...
2      [data, analyst, are, you, a, detail, oriented,...
3      [data, analyst, a, day, in, the, life, of, an,...
4      [data, analyst, key, responsibilities, work, o...
                             ...
160    [business, analyst, about, turing, turing, is,...
161    [business, analyst, role, overview, we, are, l...
162    [analytics, company, overviewuptrail, is, a, u...
163    [data, analyst, company, descriptiondelta, ana...
164    [analytics, assist, in, collecting, cleaning, ...
Name: tokens, Length: 165, dtype: object

In [16]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [17]:
def stopwords_removal(tokens):
    stop_words = set(stopwords.words("english"))
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return filtered_tokens

df['filtered_tokens'] = df['tokens'].apply(stopwords_removal)

In [18]:
df['filtered_tokens']

0      [data, analyst, detail, oriented, individual, ...
1      [data, analyst, day, life, online, data, analy...
2      [data, analyst, detail, oriented, individual, ...
3      [data, analyst, day, life, online, data, analy...
4      [data, analyst, key, responsibilities, work, p...
                             ...
160    [business, analyst, turing, turing, one, world...
161    [business, analyst, role, overview, looking, c...
162    [analytics, company, overviewuptrail, uk, base...
163    [data, analyst, company, descriptiondelta, ana...
164    [analytics, assist, collecting, cleaning, anal...
Name: filtered_tokens, Length: 165, dtype: object

In [19]:
from nltk.stem import WordNetLemmatizer
nltk.download("wordnet")
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [20]:
df["lemmatized_tokens"] = df["filtered_tokens"].apply(lambda tokens: [lemmatizer.lemmatize(token , pos = "v") for token in tokens])

In [21]:
df["lemmatized_tokens"][0]

['data',
 'analyst',
 'detail',
 'orient',
 'individual',
 'passion',
 'research',
 'good',
 'understand',
 'national',
 'local',
 'geography',
 'opportunity',
 'allow',
 'work',
 'pace',
 'comfort',
 'home',
 'key',
 'responsibilities',
 'work',
 'project',
 'aim',
 'enhance',
 'content',
 'quality',
 'digital',
 'map',
 'use',
 'millions',
 'people',
 'worldwide',
 'complete',
 'research',
 'evaluation',
 'task',
 'web',
 'base',
 'environment',
 'verify',
 'compare',
 'data',
 'determine',
 'relevance',
 'accuracy',
 'information',
 'join',
 'us',
 'today',
 'part',
 'dynamic',
 'innovative',
 'team',
 'make',
 'difference',
 'world',
 'telus',
 'digital',
 'ai',
 'community',
 'global',
 'ai',
 'community',
 'vibrant',
 'network',
 'million',
 'contributors',
 'diverse',
 'background',
 'help',
 'customers',
 'collect',
 'enhance',
 'train',
 'translate',
 'localize',
 'content',
 'build',
 'better',
 'ai',
 'model',
 'become',
 'part',
 'grow',
 'community',
 'make',
 'impact',
 'support',
 'machine',
 'learn',
 'model',
 'world',
 'largest',
 'brand',
 'qualification',
 'path',
 'previous',
 'professional',
 'experience',
 'require',
 'apply',
 'role',
 'however',
 'work',
 'project',
 'require',
 'pass',
 'basic',
 'requirements',
 'go',
 'standard',
 'assessment',
 'process',
 'part',
 'time',
 'long',
 'term',
 'project',
 'work',
 'subject',
 'standard',
 'quality',
 'assurance',
 'check',
 'term',
 'agreement',
 'assessment',
 'order',
 'hire',
 'program',
 'take',
 'open',
 'book',
 'qualification',
 'exam',
 'determine',
 'suitability',
 'position',
 'complete',
 'id',
 'verification',
 'team',
 'provide',
 'guidelines',
 'learn',
 'materials',
 'qualification',
 'exam',
 'require',
 'complete',
 'exam',
 'specific',
 'timeframe',
 'convenience',
 'english',
 'proficiency',
 'speak',
 'english',
 'proficiency',
 'write',
 'punjabi',
 'proficiency',
 'speak',
 'punjabi',
 'proficiency',
 'write',
 'artificial',
 'intelligence']

In [22]:
# skill matching 
df["processed_text"] = df["lemmatized_tokens"].apply(lambda x: " ".join(x))

In [23]:
df["processed_text"]

0      data analyst detail orient individual passion ...
1      data analyst day life online data analyst role...
2      data analyst detail orient individual passion ...
3      data analyst day life online data analyst role...
4      data analyst key responsibilities work project...
                             ...
160    business analyst turing turing one worlds fast...
161    business analyst role overview look candidates...
162    analytics company overviewuptrail uk base care...
163    data analyst company descriptiondelta analytic...
164    analytics assist collect clean analyze large d...
Name: processed_text, Length: 165, dtype: object

In [24]:
skills_list = ['python' ,'r','sql','java','scala','c++' ,
               'excel','power bi','tableau' ,'statistics',
               'data visualization','reporting','dashboarding' , 
               'mysql','postgresql','mongodb','snowflake','oracle' ,
               'etl','data warehousing','spark','hadoop','airflow','dbt',
               'machine learning','deep learning','nlp','tensorflow',
               'pytorch','scikit-learn','computer vision','llm' ,
               'aws','azure','gcp','databricks' ,'business analysis',
               'stakeholder management','kpi','forecasting','market research' ,
               'communication','problem solving','leadership','presentation',
               'pandas','numpy','matplotlib','seaborn','plotly','ggplot2','artificial intelligence','big data',
               'data mining','data cleaning', 'data preprocessing','data modeling','data analysis',
               'data storytelling', 'research','analysis','reporting','dashboard' ,'structured query language',
               'visualization','google sheets' , 'microsoft excel']

len(skills_list)

67

In [25]:
def skill_extracter(text):
    extracted_skills = []

    for skill in skills_list:
        
        if re.search(r'\b' + re.escape(skill) + r'\b', text):
            extracted_skills.append(skill)

    return list(set(extracted_skills))


df["extracted_skills"] = df["processed_text"].apply(skill_extracter)

In [26]:
df["skill_count"] = df["extracted_skills"].apply(len)

In [27]:
df.columns

Index(['Job Title', 'Company Name', 'Location', 'Experience Required',
       'Salary', 'Skills Required', 'Job Description', 'Posted Date',
       'Scrape Date', 'Job Link', 'Source Platform', 'Standardized_Job_Title',
       'days_sinced_posted', 'salary_min', 'salary_max', 'salary_avg',
       'Experience_Years', 'Combined_text', 'tokens', 'filtered_tokens',
       'lemmatized_tokens', 'processed_text', 'extracted_skills',
       'skill_count'],
      dtype='object')

In [ ]:
print(df[["Standardized_Job_Title", "extracted_skills", "skill_count"]].head())

  Standardized_Job_Title                     extracted_skills  skill_count
0           Data Analyst  [artificial intelligence, research]            2
1           Data Analyst                           [research]            1
2           Data Analyst                           [research]            1
3           Data Analyst  [analysis, data analysis, research]            3
4           Data Analyst                           [research]            1

In [33]:
zero_skills_df = df[df["skill_count"] == 0]

print(zero_skills_df[["Standardized_Job_Title", "Combined_text"]].head(1))

        Standardized_Job_Title  \
138  Machine Learning Engineer

                                         Combined_text
138  machine learning engineer hiring machine learn...

In [34]:
len(zero_skills_df)

1

In [47]:
all_skills = [
    skill 
    for skill_list in df['extracted_skills'] 
    for skill in skill_list
]
len(all_skills)

1050

In [48]:
# count skill frequency
from collections import Counter
skill_counts = Counter(all_skills)

In [49]:
skill_counts

Counter({'analysis': 92,
         'python': 87,
         'sql': 83,
         'data visualization': 68,
         'research': 57,
         'data analysis': 56,
         'communication': 51,
         'excel': 50,
         'power bi': 45,
         'tableau': 38,
         'etl': 35,
         'aws': 27,
         'statistics': 27,
         'big data': 22,
         'r': 21,
         'azure': 20,
         'spark': 19,
         'airflow': 18,
         'pandas': 18,
         'gcp': 17,
         'snowflake': 15,
         'tensorflow': 13,
         'numpy': 13,
         'dashboarding': 12,
         'leadership': 12,
         'nlp': 10,
         'llm': 10,
         'pytorch': 10,
         'java': 8,
         'business analysis': 8,
         'presentation': 8,
         'dbt': 8,
         'databricks': 7,
         'hadoop': 7,
         'mongodb': 6,
         'stakeholder management': 6,
         'matplotlib': 6,
         'artificial intelligence': 5,
         'kpi': 5,
         'data preprocessing': 5,
         'postgresql': 4,
         'oracle': 4,
         'seaborn': 4,
         'mysql': 3,
         'market research': 3,
         'scala': 3,
         'computer vision': 3,
         'ggplot2': 1})

In [45]:
normalization_dict = {
    "microsoft excel": "excel",
    "structured query language": "sql",
    "visualization": "data visualization",
    "dashboard": "dashboarding"
}
df['extracted_skills'] = df['extracted_skills'].apply(lambda skills: [normalization_dict.get(skill, skill) for skill in skills])

In [50]:
df.columns

Index(['Job Title', 'Company Name', 'Location', 'Experience Required',
       'Salary', 'Skills Required', 'Job Description', 'Posted Date',
       'Scrape Date', 'Job Link', 'Source Platform', 'Standardized_Job_Title',
       'days_sinced_posted', 'salary_min', 'salary_max', 'salary_avg',
       'Experience_Years', 'Combined_text', 'tokens', 'filtered_tokens',
       'lemmatized_tokens', 'processed_text', 'extracted_skills',
       'skill_count'],
      dtype='object')

In [52]:
df.to_csv(r"d:\Startup\Project\ai-career-coach\data\processed\jobs_with_skills.csv", index=False)

In [53]:
skill_freq_df = pd.DataFrame(
    skill_counts.items(),
    columns=["Skill", "Count"]
).sort_values(by="Count", ascending=False)

In [54]:
print(skill_freq_df.head(20))

                 Skill  Count
2             analysis     92
9               python     87
13                 sql     83
25  data visualization     68
1             research     57
3        data analysis     56
19       communication     51
7                excel     50
8             power bi     45
6              tableau     38
16                 etl     35
20                 aws     27
24          statistics     27
4             big data     22
23                   r     21
33               azure     20
37               spark     19
26              pandas     18
14             airflow     18
35                 gcp     17

In [55]:
skill_freq_df.to_csv(r"d:\Startup\Project\ai-career-coach\data\processed\skill_frequencies.csv", index=False)

In [56]:
role_skill_map = df.groupby("Standardized_Job_Title")["extracted_skills"].sum()

In [57]:
role_skill_map

Standardized_Job_Title
Analytics                    [snowflake, leadership, airflow, power bi, pyt...
Business Analyst             [excel, research, business analysis, analysis,...
Data Analyst                 [artificial intelligence, research, research, ...
Data Engineer                [mongodb, mysql, postgresql, sql, airflow, pow...
Data Scientist               [analysis, python, data analysis, sql, communi...
Machine Learning Engineer    [r, python, data analysis, analysis, python, a...
Other                        [big data, java, tableau, excel, power bi, pyt...
Product Analyst              [excel, communication, market research, analys...
Name: extracted_skills, dtype: object

In [59]:
role_skill_data = []

for role in df["Standardized_Job_Title"].unique():
    
    role_df = df[df["Standardized_Job_Title"] == role]
    
    role_skill = [
        skill
        for skills_list in role_df["extracted_skills"]
        for skill in skills_list
    ]

    role_skill_count = Counter(role_skill)

    for skill , count in role_skill_count.items():
        role_skill_data.append({
            "Role": role,
            "Skill": skill,
            "Count": count
        })

In [ ]:
role_skill_df = pd.DataFrame(role_skill_data)
role_skill_df.reset_index(inplace=True, drop=True)

In [65]:
role_skill_df = role_skill_df.sort_values(by=["Role" , "Count"] , ascending=[True, False])

In [67]:
role_skill_df.head()

         Role               Skill  Count
96  Analytics               excel     19
89  Analytics            power bi     16
90  Analytics              python     16
92  Analytics            analysis     16
97  Analytics  data visualization     16

In [69]:
role_skill_matrix = role_skill_df.pivot_table(
    index = 'Role' , 
    columns = 'Skill' ,
    values = 'Count' , 
    fill_value = 0
)

In [70]:
role_skill_matrix

Skill,airflow,analysis,artificial intelligence,aws,azure,big data,business analysis,communication,computer vision,dashboarding,...,research,scala,seaborn,snowflake,spark,sql,stakeholder management,statistics,tableau,tensorflow
Role,,,,,,,,,,,,,,,,,,,,,
Analytics,1.0,16.0,0.0,1.0,2.0,0.0,0.0,4.0,0.0,1.0,...,2.0,0.0,1.0,2.0,0.0,15.0,0.0,3.0,12.0,0.0
Business Analyst,0.0,11.0,0.0,0.0,0.0,0.0,6.0,3.0,0.0,0.0,...,9.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
Data Analyst,0.0,32.0,2.0,4.0,3.0,1.0,1.0,13.0,0.0,5.0,...,32.0,0.0,1.0,1.0,0.0,25.0,3.0,9.0,13.0,1.0
Data Engineer,15.0,4.0,0.0,10.0,9.0,5.0,0.0,11.0,0.0,1.0,...,1.0,2.0,0.0,8.0,11.0,21.0,2.0,1.0,4.0,0.0
Data Scientist,1.0,12.0,1.0,6.0,4.0,3.0,1.0,10.0,2.0,1.0,...,5.0,1.0,2.0,1.0,6.0,10.0,1.0,10.0,5.0,7.0
Machine Learning Engineer,0.0,3.0,2.0,2.0,2.0,1.0,0.0,2.0,1.0,0.0,...,4.0,0.0,0.0,0.0,0.0,2.0,0.0,3.0,1.0,5.0
Other,1.0,10.0,0.0,4.0,0.0,11.0,0.0,5.0,0.0,3.0,...,3.0,0.0,0.0,3.0,2.0,5.0,0.0,0.0,1.0,0.0
Product Analyst,0.0,4.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,2.0,0.0