In [62]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
import re

In [63]:

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive"
    }

job_titles = []
company_names= []
locations = []
salary = []
experience_list = []
skills_required= []
job_description = []
posted_dates = []
job_links = []

for j in range(1,16):
    url = f"https://internshala.com/jobs/analytics,data-science,machine-learning-jobs/page-{j}/"
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text , "html.parser")
      
    #extracting job titles
    for title in soup.find_all("a" , class_ = "job-title-href"):
        job_titles.append(title.text.strip())
    
    #extracting company names
    for company in soup.find_all("p" , class_ = "company-name"):
        company_names.append(company.text.strip())  
    
    #extracting locations
    for loc in soup.find_all("div", class_="individual_internship"):
        location_tag = loc.select_one("p.row-1-item.locations span a")
        if location_tag:
            locations.append(location_tag.get_text(strip=True)) 
        else:
            locations.append(None)
    
    #extracting salary
    for job in soup.find_all("div", class_="individual_internship"):
        salary_tag = job.select_one("i.ic-16-money + span")
    
        if salary_tag:
            salary.append(salary_tag.get_text(strip=True))
        else:
            salary.append(None)
       
    #extracting experience
    for exp in soup.find_all("div", class_="individual_internship_details"):
        exp_tag = exp.select_one("i.ic-16-briefcase + span")
        if exp_tag:
            experience = exp_tag.get_text(strip=True)
            experience_list.append(experience)
        else:
            experience_list.append(None)
    
    #extracting skills required
    for job in soup.find_all("div", class_="individual_internship"):
        skill_tags = job.select("div.job_skills div.job_skill")
        skills = [skill.get_text(strip=True) for skill in skill_tags]
        skills_required.append(skills)
    
    #extracting job description
    for des in soup.find_all("div", class_="individual_internship_details"):
        des_tag = des.select_one("div.about_job div.text")
        if des_tag:
            description = des_tag.get_text(strip=True)
        job_description.append(description)
    
    #extracting posted dates
    for job in soup.find_all("div", class_="internship_meta"):
        date = job.select_one("div.detail-row-2 div.color-labels span")
        posted_dates.append(date.text.strip() if date else None)
    
    #extracting job links
    for link in soup.find_all("div", class_="internship_meta"):
        link_tag = link.select_one('a.job-title-href')
        if link_tag:
            job_links.append("https://internshala.com" + link_tag['href'])

time.sleep(1)

In [64]:
print(len(job_titles))
print(len(company_names))
print(len(locations))
print(len(salary))
print(len(experience_list))
print(len(skills_required))
print(len(job_description))
print(len(posted_dates))
print(len(job_links))

610
610
610
610
610
610
610
610
610

Creating DataFrame

In [65]:
data = pd.DataFrame({
    "Job Title": job_titles,
    "Company Name": company_names,
    "Location": locations,
    "Experience Required": experience_list,
    "Salary" : salary,
    "Skills Required": skills_required,
    "Job Description": job_description,
    "Posted Date": posted_dates,
    "Scrape Date": pd.Timestamp.now().date(),
    "Job Link" : job_links ,
    "Source Platform": "Internshala" , 
    
    })

In [66]:
data.head()

,Job Title,Company Name,Location,Experience Required,Salary,Skills Required,Job Description,Posted Date,Scrape Date,Job Link,Source Platform
0,Telegram Trader,Trading Fox Private Limited,Jaipur,No experience required,"₹ 2,00,000 - 2,50,000","[Data Analytics, Technical Analysis, Equity Re...",As a Telegram Trader at Trading Fox Private Li...,2 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-tel...,Internshala
1,Junior Search Engine Optimization (SEO) Executive,IWrite India,Delhi,1 year(s),"₹ 3,00,000 - 4,00,000","[Google Analytics, Search Engine Marketing (SE...","As a Junior SEO Executive at IWrite India, you...",2 days ago,2026-04-28,https://internshala.com/job/detail/junior-sear...,Internshala
2,Robotics Educator,Skill Bharat Association,Mumbai,1 year(s),"₹ 2,00,000 - 4,50,000","[Python, Robotics, Teaching, Community Managem...",Key Responsibilities:\r\n\r\n1. Conduct roboti...,2 weeks ago,2026-04-28,https://internshala.com/job/detail/robotics-ed...,Internshala
3,Artificial Intelligence (AI) Executive,Tidal7 Asia - A J7 Agency,Mumbai,1 year(s),"₹ 2,00,000 - 4,00,000","[Generative AI Development, Generative AI Tool...",Tidal7 (a J7 agency) is at the forefront of th...,1 week ago,2026-04-28,https://internshala.com/job/detail/artificial-...,Internshala
4,Robotics Engineer,Playto Labs,Bangalore,No experience required,"₹ 3,00,000 - 3,25,000","[Python, ARM Microcontroller, Embedded Systems...",Key Responsibilities:\r\n\r\n1. Work on roboti...,1 day ago,2026-04-28,https://internshala.com/job/detail/fresher-rob...,Internshala

In [67]:
data.shape

(610, 11)

In [80]:
relevant_keywords = [
    "data analyst",
    "data scientist",
    "business analyst",
    "machine learning",
    "data engineer",
    "product analyst",
    "analytics",
    "bi",
    "etl"
]

# Create regex pattern
pattern = "|".join(re.escape(keyword) for keyword in relevant_keywords)

# Filter rows based on job title
df = data[data["Job Title"].str.contains(pattern, case=False, na=False)]

df.reset_index(drop=True, inplace=True)
df.head()

,Job Title,Company Name,Location,Experience Required,Salary,Skills Required,Job Description,Posted Date,Scrape Date,Job Link,Source Platform
0,Punjabi-Speaking Online Data Analyst,"TELUS International AI Inc. (Las Vegas, United...",Work from home,No experience required,"₹ 4,50,000 - 4,60,000","[English Proficiency (Spoken), English Profici...",Are you a detail-oriented individual with a pa...,6 days ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala
1,Malayalam Language Data Analyst For Online,"TELUS International AI Inc. (Las Vegas, United...",Work from home,No experience required,"₹ 4,50,000 - 4,60,000",[Data Analytics],A Day in the Life of an Online Data Analyst: I...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala
2,Online Data Analyst – Marathi Speaker,"TELUS International AI Inc. (Las Vegas, United...",Work from home,No experience required,"₹ 4,50,000 - 4,60,000",[Data Analytics],Are you a detail-oriented individual with a pa...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala
3,Online Data Analyst - Gujarati Language,"TELUS International AI Inc. (Las Vegas, United...",Work from home,No experience required,"₹ 4,50,000 - 4,60,000",[Data Analysis],A Day in the Life of an Online Data Analyst:\r...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala
4,Remote Online Data Analyst (Urdu-Speaking),"TELUS International AI Inc. (Las Vegas, United...",Work from home,No experience required,"₹ 4,50,000 - 4,60,000","[Urdu Proficiency(Spoken), Urdu Proficiency(Wr...",Key Responsibilities: \r\n\r\n1. Work on a pro...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala

In [81]:
df.shape

(166, 11)

In [79]:
df["Job Title"].values

array(['Artificial Intelligence (AI) Executive', 'AI Generalist',
       'AI Agent And Tool Associate', 'Robotics Trainer',
       'Artificial Intelligence (AI) Executive',
       'Artificial Intelligence (AI) Executive',
       'Management Trainee - Prompt Engineering',
       'Punjabi-Speaking Online Data Analyst',
       'Malayalam Language Data Analyst For Online',
       'Online Data Analyst – Marathi Speaker',
       'Online Data Analyst - Gujarati Language',
       'Remote Online Data Analyst (Urdu-Speaking)',
       'Remote Online Data Analyst (Tamil-Speaking)',
       'Big Data Associate', 'Data Annotator', 'Senior Data Engineer',
       'Data/Analytics Lead',
       'Senior Frontend Engineer & AI-Powered Interactive Design',
       'Senior ETL Consultant',
       'SAP Controller & AI Executive (For Mines Industry)',
       'Generative AI Architect (Code Generation)', 'Gen AI Engineer',
       'Junior Data Scientist', 'AI Developer',
       'Digital Market Intelligence Analyst',
       'AI Marketing Specialist (Automation)',
       'Technical Recruiter (Full Stack, Data & AI Hiring)',
       'Data Analytics', 'Junior Machine Learning Associate',
       'Data Analyst',
       'Embedded Firmware Engineer (Ambarella / Linux / Edge AI)',
       'Big Data Trainee', 'Big Data Trainee',
       'Financial Analyst - Forecasting And Modelling',
       'Data Analytics Associate', 'Data Analytics Specialist',
       'Agentic AI Developer', 'AI Engineer (Full Stack)',
       'Generative AI Engineer', 'AI Engineer',
       'Artificial Intelligence (AI) Specialist',
       'Data Analytics Specialist', 'Junior Data Analytics Associate',
       'Data Analytics Executive', 'Data Analytics Executive',
       'Data Structures & Algorithms (DSA) Trainer', 'Business Analyst',
       'Junior Artificial Intelligence (AI) Executive',
       'AI/Machine Learning Mentor For Kids (Freelance)',
       'Junior Web Analytics Developer', 'Junior Data Analyst',
       'Business Analyst', 'Analyst - Security & Risk',
       'Junior Big Data Specialist', 'Big Data Trainee',
       'Senior Big Data Specialist', 'Data & Analytics Engineer',
       'Junior Big Data Trainee',
       'AI Prompt Engineer (Claude AI Specialist)',
       'Data Analytics Executive',
       'Junior AI Engineer (GenAI/Agentic AI)',
       'Data Analytics Executive', 'Data Analytics Executive',
       'Data Service Executive', 'Data Analyst', 'Data Entry Operator',
       'Management Information Systems Analyst',
       'Data Analyst (Punjabi Speaker)', 'Data Analyst (Bengali Speaker)',
       'Data Analyst (Gujarati Speaker)',
       'Data Analyst (Kannada Speaker)', 'Data Analyst (Marathi Speaker)',
       'Data Analyst (Odia/Oriya Speaker)',
       'Data Analyst (English Speaker)', 'Data Analyst (Urdu Speaker)',
       'Data Analyst (Malayalam Speaker)',
       'Data Analyst (Punjabi Speaker)', 'Data Analyst (Bengali Speaker)',
       'Data Analyst (Gujarati Speaker)',
       'Data Analyst (Kannada Speaker)', 'Data Analyst (Marathi Speaker)',
       'Data Analyst (Odia/Oriya Speaker)',
       'Data Analyst (English Speaker)', 'Data Analyst (Telugu Speaker)',
       'Data Analyst (Tamil Speaker)', 'Data Analyst (English Speaker)',
       'AI Agent Engineers',
       'Clinical AI Specialist – Medical Doctor (MBBS)',
       'Associate Business Analyst',
       'Artificial Intelligence (AI) Associate',
       'Financial Business Analyst', 'Data Executive',
       'Dental Image Annotation Specialist (Dentist - AI Project)',
       'Clinical Psychologist (AI Healthcare Research & Advisory)',
       'Data Manager For School', 'Operations & Customer Success Analyst',
       'Artificial Intelligence (AI) Executive', 'Business Analyst',
       'Artificial Intelligence (AI) Associate',
       'Junior Big Data Executive', 'Big Data Specialist', 'AI Engineer',
       'Business Analyst', 'AI Agent And Tool Associate',
       'Managed Services Analyst (Enterprise Client Success)',
       'Junior Financial Analyst',
       'Data Entry Executive (Part Time-Work From Home Job)',
       'Computer/Data Entry Operator – Part-Time/Work From Home Job',
       'Computer/Data Entry Operator – Part-Time/Work From Home',
       'Data Entry Executive (Work-from-home)', 'Paid Ads Specialist',
       'Data Entry Associate', 'Financial Analyst',
       'Data Analytics Executive',
       'Data Entry Executive (Part Time-Work From Home Job)',
       'Agentic AI Associate', 'AI-Powered Full-Stack Developer',
       'AI Video Creator', 'Data Analytics Executive',
       'AI/ML Engineer Trainee', 'Junior Business Analyst',
       'Business Analyst', 'Artificial Intelligence (AI) Manager',
       'Paid Media Associate', 'Data Analyst - Financial Markets',
       'Junior Machine Learning Specialist', 'Python AI Developer',
       'Executive - Campaign Operations (Affiliate Media)',
       'Robotics Trainer', 'Artificial Intelligence (AI) Executive',
       'Growth & Digital Marketing Associate (AI Startup)',
       'AI And ML Engineer', 'Associate Business Analyst',
       'AI Developer Trainee', 'Data Engineer', 'Data Research Executive',
       'AI Generalist', 'Robotics And AI Trainer', 'Data Extractor',
       'GEN AI Mentor', 'AI-Powered Content Creator',
       'AI-native Software Developer Intern',
       'AI Image Generation Executive',
       'AI Developer For App And Enterprise Solutions',
       'Business Analyst', 'Revenue Analyst', 'Robotics Trainer',
       'Data Analyst', 'AI Automation Engineer', 'STEM Trainer',
       'AI Software Developer', 'Junior Strategy Analyst',
       'Artificial Intelligence (AI) Executive', 'Business Analyst',
       'AI Filmmaker / AI Artist',
       'AI Expert (AI Tools & Prompt Specialist)',
       'AI Website Builder (Claude Code Specialist)', 'AI Solutions Lead',
       'Growth Marketing Executive - B2C Training Division',
       'Data Analytics Executive',
       'Workshop Presenter — AI & Financial Literacy (Freelance)',
       'Data Analyst', 'AI Agent Developer', 'Web Developer (AI First)',
       'Speech AI Intern (ASR & TTS)',
       'Artificial Intelligence (AI) Specialist',
       'Artificial Intelligence (AI) Associate',
       'Artificial Intelligence (AI) Trainee',
       'Video Editor & Cinematographer With Expertise Using AI',
       'Associate Business Analyst',
       'Artificial Intelligence (AI) Associate',
       'Robotics Trainer/STEM Trainer', 'AI Engineer',
       'AI Growth Marketer', 'Artificial Intelligence (AI) Associate',
       'Lead Research Analyst', 'Data Annotation Reviewer (AI/ML)',
       'Full Stack Developer – AI Applications (Python + React) | Fresher',
       'Data Collection Executive',
       'Artificial Intelligence (AI) Specialist', 'Powerstacker Trainee',
       'Forex Trading Analyst',
       'Remote Backend Django Engineer – AI & Algorithmic Systems',
       'Business Analyst', 'AI Annotation Specialist',
       'Databricks Consultant', 'Gen AI - Engineer',
       'Analytics Consultant', 'AI Consultant',
       'AI Specialist (AI Engineer/Design Researcher)',
       'AI/ML Engineer  Agentic Systems (Machine Learning Engineer)',
       'AI Graphic Designer', 'AI Integration Engineer',
       'Software Development Engineer R&D (Data/AI/ML/NLP)',
       'Product Analyst', 'Data Steward',
       'SEO And AI Optimization Specialist', 'Data Engineer',
       'Data Science Trainer -Offline Center Raipur', 'Analyst',
       'Online Data Analyst - Odia Language.', 'Data Analyst',
       'Data Analyst Trainer | Sholinganallur | Full Time',
       'Accordion India - Associate - Data & Analytics Consuting',
       'GRM Data Analyst',
       'Data Engineering Trainer (ETL, Big Data) | Sholinganallur | Full-Time',
       'Data Analyst', 'RAG AI Developer (LLM + Retrieval)  EdTech',
       'Generative AI Engineer',
       'Technical Writer  AI & Clinical Evaluations',
       'Postdoctoral Research Scientist', 'Gen AI Engineer',
       'Full Stack AI Engineer', 'Analyst - T&S', 'Product Analyst',
       'Machine Learning Engineer', 'AI Data Trainer',
       'Data Science Trainer',
       'BI Consultant  SQL, Power BI, AWS (ETL & Data Warehousing)-Australia Based IT Co-Pune(Hybrid)',
       'AI Video Editor', 'Ecommerce Analyst', 'Senior Data Engineer',
       'GCP Trainer', 'Senior - Data Scientist', 'Senior Data Engineer',
       'Data Engineer - Spark', 'Machine Learning Engineer',
       'Data Analyst',
       'Junior Consultant - Data Engineering - DBT / SQL / Snowflake',
       'CDP  Tech Data Analyst', 'Data Analyst', 'Data Engineer',
       'Product Engineer (AutoTechs AI Studio)', 'Master Data Manager',
       'Data Scientist', 'Analyst', 'Data Engineer (Gujarat - Onsite)',
       'Data Scientist', 'Junior Data Scientist',
       'Generative AI Engineer',
       'Data Engineer / Data Scientist  Trainer',
       'Senior Officer - AI Styling', 'Ecommerce Analyst - Operations',
       'Databricks And GenAI Roles (Engineer/ Architect)',
       'Data Engineer', 'Data Engineer (Databricks)',
       'AI Automation Engineer',
       'Palantir AIP Enterprise Roles (Engineer/ Architect)',
       'Senior Data Analyst', 'Machine Learning Engineer',
       'AI Solution Engineer', 'Machine Learning Engineer',
       'Associate Legal Counsel (Legal-AI / IP Team)',
       'TPC Analyst (Trade Product Control)', 'Research Engineer  AI/ML',
       'Customer Relationship Management Analyst Salesforce',
       'Data Engineer [T500-25273]',
       'Academic & Research Associate  Computing, Data Science, AI',
       'Junior Data Analyst', 'Engineer, Data [T500-25190]',
       'Research Analyst', 'AI/ML Data Scientist - Investment',
       'Data Scientist',
       'SDE II Back End Developer (Python, AI/ ML, DevOps)',
       'Senior Analyst / Lead Analyst  Strategic Finance',
       'Machine Learning Engineer', 'Programmer (Data Acquisition)',
       'Data Analyst - Commodity Risk Management [T500-24841]',
       'SEO Analyst  AEO/AI Search (SaaS B2B)', 'Data Analyst',
       'Data Analyst', 'Data Analyst', 'Data Analys',
       'AI Automation Engineer', 'AI Engineer',
       'Research Associate (with Survey Data And Quantitative Insights Specialization)',
       'Walkin Drive For ETL QA With ETL Testing On 17th April 26 At Pune',
       'Senior Analyst/Specialist/Manager  SMART Underwriting (Casualty)',
       'AI Thematic Expert', 'Data Analyst',
       'BBRC - Associate Scientist - Image Analyst',
       'Inventory Planning & Replenishment Analyst', 'Data Engineer',
       'Investment Analyst - VC Firm- CTC Upto 22 LPA', 'Data Scientist',
       'Procurement Analyst', 'Analyst', 'Bigdata Support',
       'Analyst, Pricing & Underwriting', 'Data Engineer', 'Analyst',
       'Data Engineer [T500-25133]',
       'Research Analyst (Modelling) In Max Institute Of Healthcare Management',
       'Data Analyst', 'Data Analyst  OT & Visualization [T500-24610]',
       'Analyst', 'AI Artist', 'Product Analyst - IIT/ NIT',
       'Data Analyst - Google Sheets, SQL, Linux/Unix', 'Data Scientist',
       'Data Engineer [T500-25102]', 'Sourcing Process Analyst',
       'Senior Analyst', 'Product Analyst', 'Data Scientist',
       'Data Engineer [T500-24926]',
       'Technical Content Developer - Data Science & Machine Learning',
       'Accordion India - Senior AI Engineer', 'MDM Analyst [T500-24944]',
       'AI Video Editor', 'Senior Data Scientist',
       'Machine Learning Engineer',
       'Associate Data Insight Analyst [T500-24881]', 'Data Analyst',
       'Analyst - Credit & Fraud Risk', 'Financial Analyst',
       'Product Analyst', 'Programmatic Analyst', 'Delivery Analyst',
       'Financial Risk Analyst / Model Risk & Capital Markets Analyst',
       'Data Quality Analyst - CATI', 'Generative AI Engineer',
       'Operations Research Scientist / Sr. Operations Research Scientist',
       'Portfolio Data Analyst (Coimbatore)', 'Data Associate',
       'Data Scientist', 'Senior Agentic AI Engineer',
       'Associate Data Scientist',
       'AI Associate  Automation & Workflow Enablement', 'AI Scientist 1',
       'Analytic Science-Scientist I', 'Data Annotator', 'Data Engineer',
       'Data Analyst', 'Commission Analyst',
       'Content Quality Analyst - Mathematics',
       'Anaplaner - Data Modeler (Supply Chain)',
       'Associate Business Manager - Paid Media',
       'Executive  Distribution Planning & Insights (Malad,Mumbai)',
       'Machine Learning Engineer', 'Data Analytics Instructor',
       'AI Solutions Consultant', 'Digital Forensics Analyst',
       'Analyst - Data Science', 'Data Engineer - Web Scraping',
       'Data Analyst', 'Product Manager  (AI/ML)',
       'Data Warehouse Modeling & DBT Expert',
       'Machine Learning Engineer / Data Scientist',
       'Lead Data Scientist', 'Data Engineer  Data Quality & Platform',
       'AI Builder', 'Gen AI (Architect)',
       'Data Science Researcher  AI Platform', 'Lead Data Engineer',
       'Senior GCP Data Engineer',
       'Data Engineer  Data Quality & Analytics',
       'Growth & AI Marketing Manager', 'Product Manager  (AI/ML)',
       'AI Kernel Engineer', 'Data Analyst', 'AI Kernel Engineer',
       'Platform / DevOps Engineer  Data & MLOps',
       'Senior Snowflake Specialist (Data Engineer)',
       'Hadoop Data Engineer', 'Business Analyst (Finance) - 33806',
       'Analyst', 'AI Data Labeler - 53125',
       'Remote Business Analyst (Hindi) - 47745',
       'Risk Management Market Risk FRTB  Analyst',
       'Technical Instructor - AI Data Analytics & Power BI/Azure AI',
       'Data Analyst', 'Data Visualization & Reporting Engineer',
       'Computer Science (AI) - Subject Matter Expert (SME)',
       'Artificial Intelligence (AI)', 'Data Analytics',
       'ERP Implementation Consultant (Business Analyst)'], dtype=object)

In [85]:
import os

print(os.path.exists(r"d:\Startup\Project\ai-career-coach\data\data\raw"))
print(os.path.exists(r"d:\Startup\Project\ai-career-coach\data\data\processed"))

True
True

In [83]:



print(os.listdir(r"d:\Startup\Project\ai-career-coach"))

['.git', '.gitignore', 'app', 'data', 'main.py', 'notebooks', 'README.md', 'requirements.txt', 'src', 'venv']

In [84]:
print(os.listdir(r"d:\Startup\Project\ai-career-coach\data"))

['data']