In [60]:
import pandas as pd 
import re
import numpy as np

In [ ]:
df = pd.read_csv(r'd:\Startup\Project\ai-career-coach\data\processed\jobs_filtered.csv')

In [62]:
df.head()

,Job Title,Company Name,Location,Experience Required,Salary,Skills Required,Job Description,Posted Date,Scrape Date,Job Link,Source Platform
0,Punjabi-Speaking Online Data Analyst,"TELUS International AI Inc. (Las Vegas, United...",Work from home,No experience required,"₹ 4,50,000 - 4,60,000","['English Proficiency (Spoken)', 'English Prof...",Are you a detail-oriented individual with a pa...,6 days ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala
1,Malayalam Language Data Analyst For Online,"TELUS International AI Inc. (Las Vegas, United...",Work from home,No experience required,"₹ 4,50,000 - 4,60,000",['Data Analytics'],A Day in the Life of an Online Data Analyst: I...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala
2,Online Data Analyst – Marathi Speaker,"TELUS International AI Inc. (Las Vegas, United...",Work from home,No experience required,"₹ 4,50,000 - 4,60,000",['Data Analytics'],Are you a detail-oriented individual with a pa...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala
3,Online Data Analyst - Gujarati Language,"TELUS International AI Inc. (Las Vegas, United...",Work from home,No experience required,"₹ 4,50,000 - 4,60,000",['Data Analysis'],A Day in the Life of an Online Data Analyst:\r...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala
4,Remote Online Data Analyst (Urdu-Speaking),"TELUS International AI Inc. (Las Vegas, United...",Work from home,No experience required,"₹ 4,50,000 - 4,60,000","['Urdu Proficiency(Spoken)', 'Urdu Proficiency...",Key Responsibilities: \r\n\r\n1. Work on a pro...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala

In [63]:
df.shape

(165, 11)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Job Title            165 non-null    object
 1   Company Name         165 non-null    object
 2   Location             164 non-null    object
 3   Experience Required  164 non-null    object
 4   Salary               165 non-null    object
 5   Skills Required      165 non-null    object
 6   Job Description      165 non-null    object
 7   Posted Date          165 non-null    object
 8   Scrape Date          165 non-null    object
 9   Job Link             165 non-null    object
 10  Source Platform      165 non-null    object
dtypes: object(11)
memory usage: 14.3+ KB

In [65]:
df.duplicated().sum()

np.int64(0)

In [66]:
df.isnull().sum()

Job Title              0
Company Name           0
Location               1
Experience Required    1
Salary                 0
Skills Required        0
Job Description        0
Posted Date            0
Scrape Date            0
Job Link               0
Source Platform        0
dtype: int64

In [67]:
df["Location"].fillna("Not Specified", inplace=True)
df["Experience Required"].fillna("Not Specified", inplace=True)

Standardize job titles

In [68]:
def standardize_job_title(title):
    title = title.lower()

    if "data analyst" in title:
        return "Data Analyst"
    elif "data scientist" in title:
        return "Data Scientist"
    elif "business analyst" in title:
        return "Business Analyst"
    elif "machine learning" in title:
        return "Machine Learning Engineer"
    elif "data engineer" in title:
        return "Data Engineer"
    elif "product analyst" in title :
        return "Product Analyst"
    elif "analytics" in title:
        return "Analytics"
    else:
        return "Other"
    
df["Standardized_Job_Title"] = df["Job Title"].apply(standardize_job_title)

In [69]:
df["Standardized_Job_Title"].value_counts()

Standardized_Job_Title
Data Analyst                 55
Data Engineer                26
Analytics                    21
Data Scientist               16
Other                        15
Business Analyst             15
Machine Learning Engineer    12
Product Analyst               5
Name: count, dtype: int64

Normalize Posting Dates

In [70]:
def normalize_posting_date(date_str):
    date_str =  str(date_str).lower()

    if 'few' in date_str or 'hour' in date_str or 'today' in date_str:
        return 0 
    elif 'day' in date_str:
        num = re.search(r'\d+' , date_str)
        return int(num.group()) if num else 1 
    elif 'week' in date_str:
        num = re.search(r'\d+' , date_str)
        return int(num.group())*7 if num else 7
    elif 'month' in date_str:
        num = re.search(r'\d+' , date_str)
        return int(num.group())*30 if num else 30
    elif "30+" in date_str:
        return 30
    else:
        None

df["days_sinced_posted"] = df["Posted Date"].apply(normalize_posting_date)

In [71]:
df["days_sinced_posted"].value_counts()

days_sinced_posted
21.0    51
7.0     45
14.0    28
5.0     11
4.0      8
3.0      7
6.0      5
0.0      4
1.0      3
2.0      2
Name: count, dtype: int64

In [72]:
df["Source Platform"].value_counts()

Source Platform
Internshala    165
Name: count, dtype: int64

In [73]:
df["Salary"].value_counts()

Salary
Competitive salary          88
₹ 3,60,000 - 7,00,000       19
₹ 4,50,000 - 4,60,000        6
₹ 4,00,000 - 7,00,000        5
₹ 5,00,000 - 6,00,000        3
₹ 3,00,000 - 4,00,000        3
₹ 6,00,000 - 8,00,000        2
₹ 4,00,000 - 5,00,000        2
₹ 5,00,000                   2
₹ 3,00,000 - 8,00,000        2
₹ 3,00,000 - 3,60,000        2
₹ 2,00,000 - 3,00,000        2
₹ 12,00,000 - 14,00,000      1
₹ 18,00,000 - 24,00,000      1
₹ 25,00,000 - 32,00,000      1
₹ 25,00,000 - 35,00,000      1
₹ 3,35,000 - 5,50,000        1
₹ 6,00,000 - 10,00,000       1
₹ 7,00,000 - 9,00,000        1
₹ 7,25,000 - 8,00,000        1
₹ 5,50,000 - 6,00,000        1
₹ 4,50,000 - 5,00,000        1
₹ 4,50,000 - 5,50,000        1
₹ 5,00,000 - 6,50,000        1
₹ 5,50,000 - 6,50,000        1
₹ 3,60,000 - 4,20,000        1
₹ 3,60,000 - 4,80,000        1
₹ 4,00,000 - 4,25,000        1
₹ 4,00,000 - 6,00,000        1
₹ 4,20,000 - 6,00,000        1
₹ 3,00,000 - 7,00,000        1
₹ 3,00,000 - 5,00,000        1
₹ 3,10,000 - 4,70,000        1
₹ 2,52,000 - 4,20,000        1
₹ 2,90,000 - 5,40,000        1
₹ 2,40,000                   1
₹ 2,40,000 - 3,60,000        1
₹ 2,00,000 - 4,00,000        1
₹ 2,00,000 - 2,50,000        1
$ 10,000                     1
₹ 10,000 - 17,000 /month     1
Name: count, dtype: int64

In [74]:
df["Salary"].replace( np.nan , "nan" , inplace=True)

In [ ]:

# Function to process salary
def clean_salary(salary_text):
    salary_text = str(salary_text).strip()

    # Case 1: Competitive / unspecified salary
    if "competitive" in salary_text.lower() or salary_text == "nan":
        return pd.Series([np.nan, np.nan, np.nan])

    # Remove ₹ symbol and commas
    cleaned = salary_text.replace("₹", "").replace(",", "").strip()

    # Case 2: Salary range
    if "-" in cleaned:
        parts = cleaned.split("-")

        try:
            salary_min = int(parts[0].strip())
            salary_max = int(parts[1].strip())
            salary_avg = (salary_min + salary_max) / 2

            return pd.Series([salary_min, salary_max, salary_avg])

        except:
            return pd.Series([np.nan, np.nan, np.nan])

    # Case 3: Fixed salary
    else:
        try:
            salary_value = int(cleaned.strip())

            return pd.Series([salary_value, salary_value, salary_value])

        except:
            return pd.Series([np.nan, np.nan, np.nan])


# Apply function
df[["salary_min", "salary_max", "salary_avg"]] = df["Salary"].apply(clean_salary)


# Optional: Fill missing values
df["salary_min"] = df["salary_min"].fillna(np.nan)
df["salary_max"] = df["salary_max"].fillna(np.nan)
df["salary_avg"] = df["salary_avg"].fillna(np.nan)



print("Salary cleaning completed successfully!")
print(df[["Salary", "salary_min", "salary_max", "salary_avg"]].head(10))

Salary cleaning completed successfully!
                    Salary  salary_min  salary_max  salary_avg
0    ₹ 4,50,000 - 4,60,000    450000.0    460000.0    455000.0
1    ₹ 4,50,000 - 4,60,000    450000.0    460000.0    455000.0
2    ₹ 4,50,000 - 4,60,000    450000.0    460000.0    455000.0
3    ₹ 4,50,000 - 4,60,000    450000.0    460000.0    455000.0
4    ₹ 4,50,000 - 4,60,000    450000.0    460000.0    455000.0
5    ₹ 4,50,000 - 4,60,000    450000.0    460000.0    455000.0
6    ₹ 3,35,000 - 5,50,000    335000.0    550000.0    442500.0
7  ₹ 25,00,000 - 35,00,000   2500000.0   3500000.0   3000000.0
8  ₹ 25,00,000 - 32,00,000   2500000.0   3200000.0   2850000.0
9  ₹ 18,00,000 - 24,00,000   1800000.0   2400000.0   2100000.0

In [79]:
df.head()

,Job Title,Company Name,Location,Experience Required,Salary,Skills Required,Job Description,Posted Date,Scrape Date,Job Link,Source Platform,Standardized_Job_Title,days_sinced_posted,salary_min,salary_max,salary_avg
0,Punjabi-Speaking Online Data Analyst,"TELUS International AI Inc. (Las Vegas, United...",Work from home,No experience required,"₹ 4,50,000 - 4,60,000","['English Proficiency (Spoken)', 'English Prof...",Are you a detail-oriented individual with a pa...,6 days ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala,Data Analyst,6.0,450000.0,460000.0,455000.0
1,Malayalam Language Data Analyst For Online,"TELUS International AI Inc. (Las Vegas, United...",Work from home,No experience required,"₹ 4,50,000 - 4,60,000",['Data Analytics'],A Day in the Life of an Online Data Analyst: I...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala,Data Analyst,21.0,450000.0,460000.0,455000.0
2,Online Data Analyst – Marathi Speaker,"TELUS International AI Inc. (Las Vegas, United...",Work from home,No experience required,"₹ 4,50,000 - 4,60,000",['Data Analytics'],Are you a detail-oriented individual with a pa...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala,Data Analyst,21.0,450000.0,460000.0,455000.0
3,Online Data Analyst - Gujarati Language,"TELUS International AI Inc. (Las Vegas, United...",Work from home,No experience required,"₹ 4,50,000 - 4,60,000",['Data Analysis'],A Day in the Life of an Online Data Analyst:\r...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala,Data Analyst,21.0,450000.0,460000.0,455000.0
4,Remote Online Data Analyst (Urdu-Speaking),"TELUS International AI Inc. (Las Vegas, United...",Work from home,No experience required,"₹ 4,50,000 - 4,60,000","['Urdu Proficiency(Spoken)', 'Urdu Proficiency...",Key Responsibilities: \r\n\r\n1. Work on a pro...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala,Data Analyst,21.0,450000.0,460000.0,455000.0

In [80]:
df[["salary_min", "salary_max", "salary_avg"]].isnull().sum()

salary_min    90
salary_max    90
salary_avg    90
dtype: int64

In [82]:
df["Location"].value_counts()

Location
Work from home    81
Bangalore         30
Maharashtra       11
Delhi              6
Nanakramguda       5
Gurgaon            4
Noida              4
Chennai            4
Ahmedabad          3
Hyderabad          2
Coimbatore         2
Mumbai             2
Yalahanka          1
Bhadrak            1
Nashik             1
Kolkata            1
Thane              1
Pune               1
Telangana          1
Indore             1
Mohali             1
Madurai            1
Not Specified      1
Name: count, dtype: int64

In [83]:
location_mapping = {
    "Work from home": "Remote",
    "Nanakramguda": "Hyderabad",
    "Yalahanka": "Bangalore",
    "Gurgaon": "Gurgaon",
    "Noida": "Noida",
    "Maharashtra": "Maharashtra",
    "Telangana": "Telangana"
}
df["Location"] = df["Location"].replace(location_mapping)

In [84]:
df['Location'].value_counts()

Location
Remote           81
Bangalore        31
Maharashtra      11
Hyderabad         7
Delhi             6
Chennai           4
Gurgaon           4
Noida             4
Ahmedabad         3
Mumbai            2
Coimbatore        2
Bhadrak           1
Pune              1
Kolkata           1
Thane             1
Nashik            1
Telangana         1
Mohali            1
Indore            1
Madurai           1
Not Specified     1
Name: count, dtype: int64

In [85]:
df["Experience Required"].value_counts()

Experience Required
No experience required    69
2 year(s)                 46
1 year(s)                 38
4 year(s)                  4
6 year(s)                  3
5 year(s)                  2
8 year(s)                  1
12 year(s)                 1
Not Specified              1
Name: count, dtype: int64

In [91]:
def extract_experience_years(exp_text):
    exp_text = exp_text.lower()

    if "no experience required" in exp_text:
        return 0
    else:
        match = re.search(r'\d+', str(exp_text))
        return int(match.group()) if match else np.nan
    
df["Experience_Years"] = df["Experience Required"].apply(extract_experience_years)

In [92]:
df["Experience_Years"].value_counts()

Experience_Years
0.0     69
2.0     46
1.0     38
4.0      4
6.0      3
5.0      2
8.0      1
12.0     1
Name: count, dtype: int64