In [1]:
import pandas as pd

In [2]:
resume_skills = [
    "sql",
    "excel",
    "power bi",
    "tableau",
    "python"
]
resume_skills = [
    skill.lower().strip()
    for skill in resume_skills
]
resume_skills = list(set(resume_skills))

In [3]:
print(resume_skills)

['python', 'tableau', 'excel', 'power bi', 'sql']

In [4]:
df = pd.read_csv(r'd:\startup\Project\ai-career-coach\data\processed\top_skills_by_role.csv')

In [5]:
df.shape

(78, 3)

In [6]:
df

   Standardized_Job_Title            Skill  Count
0               Analytics            excel     19
1               Analytics         power bi     16
2               Analytics           python     16
3               Analytics              sql     15
4               Analytics          tableau     12
..                    ...              ...    ...
73        Product Analyst          tableau      2
74        Product Analyst         big data      1
75        Product Analyst     dashboarding      1
76        Product Analyst  market research      1
77        Product Analyst              nlp      1

[78 rows x 3 columns]

In [7]:
print(
    df[
        "Standardized_Job_Title"
    ]
    .unique()
)

['Analytics' 'Business Analyst' 'Data Analyst' 'Data Engineer'
 'Data Scientist' 'Machine Learning Engineer' 'Other' 'Product Analyst']

In [8]:
# ---------------------------------------------------
# TARGET ROLE
# ---------------------------------------------------

target_role = "Data Analyst"

# ---------------------------------------------------
# NORMALIZE TARGET ROLE
# ---------------------------------------------------

target_role = (
    target_role
    .strip()
)

# ---------------------------------------------------
# FILTER ROLE BENCHMARK
# ---------------------------------------------------

role_df = (
    df[
        df[
            "Standardized_Job_Title"
        ]
        .str.strip()
        == target_role
    ]
)

# ---------------------------------------------------
# PREVIEW
# ---------------------------------------------------

print("\nTarget Role:")
print(target_role)

print("\nRole Benchmark Preview:")

print(
    role_df.head(10)
)

# ---------------------------------------------------
# VALIDATION
# ---------------------------------------------------

print("\nShape:")
print(role_df.shape)

print("\nUnique Roles:")

print(
    role_df[
        "Standardized_Job_Title"
    ].unique()
)

Target Role:
Data Analyst

Role Benchmark Preview:
   Standardized_Job_Title       Skill  Count
18           Data Analyst         sql     25
19           Data Analyst      python     21
20           Data Analyst    power bi     16
21           Data Analyst     tableau     13
22           Data Analyst       excel     12
23           Data Analyst           r     10
24           Data Analyst  statistics      9
25           Data Analyst         etl      7
26           Data Analyst      pandas      7
27           Data Analyst       numpy      6

Shape:
(10, 3)

Unique Roles:
['Data Analyst']

In [9]:
role_skills = role_df['Skill'].tolist()

In [10]:
resume_set = set(resume_skills)

role_set = set(role_skills)

In [11]:
print(type(resume_set))
print(type(role_set))

<class 'set'>
<class 'set'>

In [12]:
matched_skills = sorted(
    resume_set & role_set
)

In [13]:
print("\nMatched Skills:")

print(matched_skills)

Matched Skills:
['excel', 'power bi', 'python', 'sql', 'tableau']

In [14]:

missing_skills = sorted(
    role_set - resume_set
)

In [15]:
missing_skills

['etl', 'numpy', 'pandas', 'r', 'statistics']

In [16]:
role_skill_count = len(role_set)
matched_skills_count = len(matched_skills)

In [17]:
if len(role_set) > 0:

    match_score = (
        len(matched_skills)
        / len(role_set)
    ) * 100

else:

    match_score = 0

In [18]:
match_score = round(match_score , 2)
print(f"\nMatch Score: {match_score}%")

Match Score: 50.0%

In [19]:
match_result = {

    "Role": target_role,

    "Match Score": match_score,

    "Matched Skills": matched_skills,

    "Missing Skills": missing_skills,

    "Matched Skill Count": len(
        matched_skills
    ),

    "Missing Skill Count": len(
        missing_skills
    )
}

In [20]:
match_result

{'Role': 'Data Analyst',
 'Match Score': 50.0,
 'Matched Skills': ['excel', 'power bi', 'python', 'sql', 'tableau'],
 'Missing Skills': ['etl', 'numpy', 'pandas', 'r', 'statistics'],
 'Matched Skill Count': 5,
 'Missing Skill Count': 5}

In [29]:
pd.read_csv(r'd:\startup\Project\ai-career-coach\data\processed\data_scientist_batch_results.csv')

,Resume,Role,Match Score %,Matched Skills,Missing Skills,Matched Skill Count,Missing Skill Count
0,resume_1,Data Scientist,30.0,"numpy, python, sql","aws, data preprocessing, pandas, pytorch, spar...",3,7
1,resume_2,Data Scientist,20.0,"python, sql","aws, data preprocessing, numpy, pandas, pytorc...",2,8
2,resume_3,Data Scientist,20.0,"python, sql","aws, data preprocessing, numpy, pandas, pytorc...",2,8
3,resume_4,Data Scientist,30.0,"numpy, python, sql","aws, data preprocessing, pandas, pytorch, spar...",3,7
4,resume_5,Data Scientist,10.0,python,"aws, data preprocessing, numpy, pandas, pytorc...",1,9
5,resume_6,Data Scientist,10.0,python,"aws, data preprocessing, numpy, pandas, pytorc...",1,9
6,resume_7,Data Scientist,10.0,python,"aws, data preprocessing, numpy, pandas, pytorc...",1,9
7,resume_8,Data Scientist,10.0,python,"aws, data preprocessing, numpy, pandas, pytorc...",1,9
8,resume_9,Data Scientist,10.0,python,"aws, data preprocessing, numpy, pandas, pytorc...",1,9
9,resume_10,Data Scientist,30.0,"numpy, python, sql","aws, data preprocessing, pandas, pytorch, spar...",3,7
10,resume_11,Data Scientist,20.0,"python, sql","aws, data preprocessing, numpy, pandas, pytorc...",2,8
11,resume_12,Data Scientist,20.0,"python, sql","aws, data preprocessing, numpy, pandas, pytorc...",2,8
12,resume_13,Data Scientist,30.0,"numpy, python, sql","aws, data preprocessing, pandas, pytorch, spar...",3,7
13,resume_14,Data Scientist,30.0,"numpy, python, sql","aws, data preprocessing, pandas, pytorch, spar...",3,7
14,resume_15,Data Scientist,30.0,"numpy, python, sql","aws, data preprocessing, pandas, pytorch, spar...",3,7